# SportApp Mobile - Finalization Plan

The goal is to transform the existing skeleton into a professional-grade "final version" by implementing the missing AI Coach, Chat, and Photo Saving features.

## User Review Required

> [!IMPORTANT]
> **Cloudinary Configuration**: Saving photos requires Cloudinary credentials on the backend. Please ensure `CLOUDINARY_CLOUD_NAME`, `CLOUDINARY_API_KEY`, and `CLOUDINARY_API_SECRET` are set in the backend `.env`.
> 
> **Gemini API Check**: The AI Coach and AI Scan require a valid Gemini API key. Ensure it's configured in the app settings or backend.

## Proposed Changes

We will overhaul the mobile app architecture to include these core pillars:

### 1. AI Coach Chat (`AiCoachScreen`)
A new conversational interface where the user can talk to an AI Trainer.
- **Service**: Update `GeminiService` to support multi-turn conversations.
- **UI**: A premium chat bubble interface with glassmorphism effects.
- **Feature**: "Haftalık Rapor Al" (Get Weekly Report) button to provide data-driven insights.

### 2. AI Scan & Photo Persistence
Enabling the "Save" functionality the user specifically mentioned.
- **Service**: 
  - **[NEW] `photo_service.dart`**: Handle multipart uploads to the `/api/photos/upload` endpoint.
  - **[NEW] `sync_service.dart`**: Handle logging meals to `/api/sync/biometrics` and calories.
- **Logic**: When the user clicks "KAYDET" (Save) after a meal scan:
  1. The photo is uploaded to Cloudinary.
  2. The calories/macros are saved to the user's daily log.

### 3. Functional Workout Module (`TrainerScreen`)
Replacing the "Preparing..." placeholder.
- **Feature**: "Günün Antrenmanı" (Workout of the Day) generated by AI.
- **Navigation**: Dedicated tab for workout tracking.

### 4. Navigation & UI Polish
- **[MODIFY] [main.dart](file:///c:/projects/SportApp/mobile_app/lib/main.dart)**:
  - Update Bottom Navigation to: **GÜNLÜK** | **ANTRENÖR** | **AI TARAMA** | **AYARLAR**.
  - Wire up the new screens.
- **[MODIFY] [theme.dart](file:///c:/projects/SportApp/mobile_app/lib/theme.dart)**:
  - Add more Neo-Dark utility styles (Blur levels, specific gradient tokens).

## Verification Plan

### Automated Tests
- `flutter run` check: Ensure no "Target of URI doesn't exist" errors.
- Mock backend tests for photo upload (simulating multipart requests).

### Manual Verification
- **Photo Saving**: Take a photo in "AI SCAN", wait for analysis, click "KAYDET", and verify it appears in the backend database/Cloudinary.
- **AI Coach**: Send a message to the coach and verify a contextual response (e.g., "I saw you ran 5km today...").
- **Health Sync**: Verify the `HealthService` we just fixed still works in the background.
